### ISSUE TITLE
ValueError: Property "m_bSilencerOn" not found for entity type "weapon_ak47"

### ISSUE THREAD

**Issue by Ayuto** [backraw/udm#6]
I haven't figured out yet when this happens, but it seems that there are some cases that pass all your checks.
```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\plugins\udm\udm.py", line 303, in on_pre_bump_weapon
    if weapon.get_property_bool('m_bSilencerOn') != inventory_item.silencer_option:
  File "..\addons\source-python\packages\source-python\entities\_base.py", line 377, in get_property_bool
    return self._get_property(name, 'bool')
  File "..\addons\source-python\packages\source-python\entities\_base.py", line 535, in _get_property
    name, self.classname))

ValueError: Property "m_bSilencerOn" not found for entity type "weapon_ak47"
```

**Comment by thetredev** [comment]
Thought I've had it already fixed. I'll see what I can do, thanks.
